name: Build Draft Release

on:
  workflow_dispatch:
    inputs:
      server-semver:
        description: Release to download for the PowerShellEditorServices repo
        required: true
      package-semver:
        description: Semantic version to release
        required: true

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Create release files
        run: ./make.sh ${{ github.event.inputs.server-semver }}
        id: create-release-files
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.package-semver }}
          release_name: Release ${{ github.event.inputs.package-semver }}
          draft: true
          prerelease: false
          body: This release contains version ${{ github.event.inputs.server-semver }} of PowerShellEditorServices.
      - name: Upload Zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./${{ steps.create-release-files.outputs.artifact }}
          asset_name: ${{ steps.create-release-files.outputs.artifact }}
          asset_content_type: application/zip
