name: Notify Repository on Published Release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-16.04
    steps:
      - name: Notify repository
        run: |
          curl -X POST https://api.github.com/repos/sublimelsp/repository/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: token ${{ secrets.RWOLS_PERSONAL_ACCESS_TOKEN }}' \
          --data '{"event_type": "lsp-add-or-update-package", "client_payload": ${{ toJson(github.event) }} }'
